"""init tables

Revision ID: 84cdd3a1070b
Revises: 
Create Date: 2025-08-17 22:47:28.026829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84cdd3a1070b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draws',
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('draw_date', sa.Date(), nullable=True),
    sa.Column('n1', sa.Integer(), nullable=True),
    sa.Column('n2', sa.Integer(), nullable=True),
    sa.Column('n3', sa.Integer(), nullable=True),
    sa.Column('n4', sa.Integer(), nullable=True),
    sa.Column('n5', sa.Integer(), nullable=True),
    sa.Column('n6', sa.Integer(), nullable=True),
    sa.Column('bonus', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('round')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=True),
    sa.Column('numbers', sa.String(length=30), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_round'), ['round'], unique=False)

    op.create_table('shops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('raw_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shops_round'), ['round'], unique=False)

    op.create_table('rec_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('rec_id', sa.Integer(), nullable=True),
    sa.Column('match_count', sa.Integer(), nullable=True),
    sa.Column('bonus_hit', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rec_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rec_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rec_scores_round'), ['round'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rec_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rec_scores_round'))

    op.drop_table('rec_scores')
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shops_round'))

    op.drop_table('shops')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_round'))

    op.drop_table('recommendations')
    op.drop_table('draws')
    # ### end Alembic commands ###
